spring.application.name=FleetFlow
spring.datasource.url=jdbc:mysql://localhost:3307/fleetflow?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=uxui2025

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
server.port=8082